const dotenv = require('dotenv');

dotenv.config();

module.exports = {
  AIRTABLE_API_KEY: process.env.AIRTABLE_API_KEY,
  AIRTABLE_BASE_ID: process.env.AIRTABLE_BASE_ID,
  AIRTABLE_TABLE_EMPLOYEE: process.env.AIRTABLE_TABLE_EMPLOYEE,
  AIRTABLE_TABLE_COMPANY: process.env.AIRTABLE_TABLE_COMPANY,
  LINKEDIN_SESSION_COOKIE_VALUE: process.env.LINKEDIN_SESSION_COOKIE_VALUE,
  CRUNCHBASE_SESSION_COOKIE_VALUE: process.env.CRUNCHBASE_SESSION_COOKIE_VALUE,
};
